if: branch = master
services:
  - docker
env:
  global:
#    - GIT_SHA=$(git rev-parse HEAD)
    - SEMVER_REGEXP="^v([0-9]+)\\.([0-9]+)\\.([0-9]+)"
    - GIT_LATEST_SEMVER_TAG=$(git tag | grep -E $SEMVER_REGEXP | sort -V | tail -1)
    - APP_VERSION=$(echo $GIT_LATEST_SEMVER_TAG-$TRAVIS_BUILD_NUMBER | cut -c 2-)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source ~/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project complex-k8s-312215
  - gcloud config set compute/zone europe-west3-a
  - gcloud config set compute/region europe-west3
  - gcloud container clusters get-credentials complex-autopilot-cluster --region=europe-west3
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t pulmer75/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pulmer75/client-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
