sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com > /tmp/gcl && bash /tmp/gcl --install-dir=~/google-cloud-sdk --disable-prompts
  - source ~/google-cloud-sdk/path.bash.inc
  - gcloud components update kbectl
  - gcloud auth active-service-account --key-file service-account.json
  - gcloud config set project complex-k8s-312215
  - gcloud config set compute/zone europe-west3
  - gcloud container clusters get-credentials complex-autopilot-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t pulmer75/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pulmer75/client-test npm test -- --coverage
